pipeline {
     agent { label 'node1' }
    tools { 
        maven 'maven'
    }
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('test-Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('test-Test') {
            steps {
                sh 'mvn test'
                 sh 'ls -l target/surefire-reports' 
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        
            }
        }


