pipeline {
     agent {
        label 'docker-agent-00002grj0tg7n' 
    }
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('master-Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('master-Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        
            }
        }


